name: GitHub Actions - Trigger
run-name: Running - ${{ github.event_name }}
on:
  workflow_run:
    workflows: [GitHub Actions - Trigger 1]
    types: [completed]
    branch: [main]
    # types: [requested]
    # types: [in_progress]
    # types: [completed,requested, in_progress]


jobs:
  on-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: |
          echo "Comentário Cron Job"