name: Github actions - Pull Request Template Basic
run-name: Running - ${{github.event_name}}
on:
  workflow_dispatch:
    inputs:
      severidade:
        description: funcionalidade crítica?
        type: boolean
jobs:
  on-workflow_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: |
          echo "${{inputs.severidade}}"      