name: Github actions - Push Template Basic
run-name: Running - ${{github.event_name}}
on: [push, workflow_dispatch]

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
    - name: Comentário
      run: |
        echo "${{ secrets.test_secret }}"      