name: Github actions - Push Template Basic
run-name: Running - ${{github.event_name}}
on:
  push:
    paths: 
      - '**.txt'
      - '**.pneg'

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
    - name: Comentário
      run: |
        echo "Comentario do workflow Push"      