name: GitHub Actions - Cron Job Template
run-name: Running - ${{ github.event_name }}
on: [push, workflow_dispatch]

jobs:
  job_1_erro: 
    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: |
          echo Comentario antes do erro
          exit 1
      - name: Comentário
        run: |
          echo Comentario após o erro 

  job_2_always_exec: 
    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: |
          echo Comentario antes do erro
          exit 1
          
      - name: Comentário
        if: always()
        run: |
          echo Comentario após o erro  
          
  job_3_continue_on_error: 
    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: |
          echo Comentario antes do erro
          exit 1
        continue-on-error: true

      - name: Comentário
        if: always()
        run: |
          echo Comentario após o erro             

