name: Github actions - Push Template Basic
run-name: Running - ${{github.event_name}}
on:
  push:
    branches:
      - develop
      - master
      - 'release/**'

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
    - name: Comentário
      run: |
        echo "Comentario do workflow Push"      