name: GitHub Actions - Cron Job Template
run-name: Running - ${{ github.event_name }}
on: [push, workflow_dispatch]

jobs:
  on-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: |
          echo "${{ vars.var_test}}"