name: GitHub Actions - Cron Job Template
run-name: Running - ${{ github.event_name }}
on: [push, workflow_dispatch]
env:
  variavel: "Bom dia"
  var_1: ${{secrets.TEST_SECRET}}
  var_2: ${{vars.VAR_TEST}}
jobs:
  on-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: |
          echo "$variavel"
          echo "$var_1"
          echo "$var_2"